name: demo-backend
services:
- name: web
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    repo: vincentwolf89/demo_backend
    branch: deploy
    deploy_on_push: true
  http_port: 8000
  health_check:
    http_path: /health
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
